// Code generated by "stringer -type=SevMode"; DO NOT EDIT.

package guest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SEV-0]
	_ = x[SEV_ES-1]
	_ = x[SEV_SNP-2]
	_ = x[SEV_SNP_SVSM-3]
}

const _SevMode_name = "SEVSEV_ESSEV_SNPSEV_SNP_SVSM"

var _SevMode_index = [...]uint8{0, 3, 9, 16, 28}

func (i SevMode) String() string {
	if i < 0 || i >= SevMode(len(_SevMode_index)-1) {
		return "SevMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SevMode_name[_SevMode_index[i]:_SevMode_index[i+1]]
}
