// Code generated by "stringer -type=VMMType"; DO NOT EDIT.

package vmmtypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QEMU-0]
	_ = x[EC2-1]
}

const _VMMType_name = "QEMUEC2"

var _VMMType_index = [...]uint8{0, 4, 7}

func (i VMMType) String() string {
	if i < 0 || i >= VMMType(len(_VMMType_index)-1) {
		return "VMMType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VMMType_name[_VMMType_index[i]:_VMMType_index[i+1]]
}
